# Generated by Django 5.2.7 on 2025-10-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15, unique=True)),
                ('eposta', models.EmailField(blank=True, max_length=100, null=True)),
                ('musteri_turu', models.CharField(choices=[('ALICI', 'Alıcı'), ('SATICI', 'Satıcı'), ('KIRACI', 'Kiracı'), ('KIRALAYAN', 'Kiralayan'), ('YATIRIMCI', 'Yatırımcı')], default='ALICI', max_length=10)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('notlar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('mülk_turu', models.CharField(choices=[('KONUT', 'Konut'), ('ISYERI', 'İşyeri'), ('ARSA', 'Arsa'), ('PROJE', 'Proje')], max_length=10)),
                ('durum', models.CharField(choices=[('SATILIK', 'Satılık'), ('KIRALIK', 'Kiralık'), ('SATILDI', 'Satıldı'), ('KIRALANDI', 'Kiralandı'), ('PASIF', 'Pasif')], default='SATILIK', max_length=10)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('brut_m2', models.IntegerField(blank=True, null=True)),
                ('net_m2', models.IntegerField(blank=True, null=True)),
                ('oda_sayisi', models.CharField(blank=True, max_length=10, null=True)),
                ('adres', models.CharField(max_length=255)),
                ('sehir', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=50)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('sahip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sahip_oldugu_mulkler', to='portfoy_yonetimi.musteri')),
            ],
        ),
    ]
