# Generated by Django 5.2.7 on 2025-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulk',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mulk_fotolari/'),
        ),
    ]
