# Generated by Django 5.2.7 on 2025-10-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0002_mulk_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mulk',
            name='foto',
        ),
        migrations.CreateModel(
            name='MulkFotografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='mulk_fotograflari/')),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('varsayilan', models.BooleanField(default=False)),
                ('mulk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='portfoy_yonetimi.mulk')),
            ],
            options={
                'verbose_name_plural': 'Mülk Fotoğrafları',
            },
        ),
    ]
