# Generated by Django 5.2.7 on 2025-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0003_remove_mulk_foto_mulkfotografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulk',
            name='bina_kat_sayisi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bina Toplam Kat Sayısı'),
        ),
        migrations.AddField(
            model_name='mulk',
            name='bulundugu_kat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bulunduğu Kat'),
        ),
    ]
