# Generated by Django 5.2.7 on 2025-10-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0004_mulk_bina_kat_sayisi_mulk_bulundugu_kat'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='iban_numarasi',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='ikametgah_adresi',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='kimlik_numarasi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
