# Generated by Django 5.2.7 on 2025-10-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0005_musteri_iban_numarasi_musteri_ikametgah_adresi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musteri',
            old_name='iban_numarasi',
            new_name='iban',
        ),
        migrations.CreateModel(
            name='MusteriEvraki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Evrak Başlığı')),
                ('evrak_turu', models.CharField(choices=[('SOZLESME', 'Mülk Satış/Kira Sözleşmesi'), ('VEKALET', 'Vekaletname'), ('TAPU', 'Tapu Belgesi'), ('KIMLIK', 'Kimlik/Nüfus Sureti'), ('DIGER', 'Diğer Evrak')], default='DIGER', max_length=10, verbose_name='Evrak Türü')),
                ('evrak_tarihi', models.DateField(blank=True, help_text='Sözleşme veya evrağın düzenlenme tarihi', null=True, verbose_name='Evrak Tarihi')),
                ('dosya', models.FileField(upload_to='musteri_evraklari/', verbose_name='Evrak Dosyası')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama/Notlar')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evraklar', to='portfoy_yonetimi.musteri')),
            ],
        ),
    ]
