# Generated by Django 5.2.7 on 2025-10-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0006_rename_iban_numarasi_musteri_iban_musterievraki'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musterievraki',
            options={'verbose_name': 'Müşteri Evrağı', 'verbose_name_plural': 'Müşteri Evrakları'},
        ),
        migrations.RemoveField(
            model_name='musterievraki',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='musterievraki',
            name='evrak_turu',
        ),
        migrations.AlterField(
            model_name='musterievraki',
            name='aciklama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musterievraki',
            name='dosya',
            field=models.FileField(help_text='Sözleşme, tapu fotokopisi vb. evrak dosyası', upload_to='musteri_evraklari/', verbose_name='Evrak Dosyası'),
        ),
    ]
