# Generated by Django 5.2.7 on 2025-10-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0007_alter_musterievraki_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musterievraki',
            name='muhatap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muhatap', to='portfoy_yonetimi.musteri'),
        ),
    ]
