# Generated by Django 5.2.7 on 2025-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0008_musterievraki_muhatap'),
    ]

    operations = [
        migrations.AddField(
            model_name='musterievraki',
            name='evrak_turu',
            field=models.CharField(choices=[('KIRA SOZLESMESI', 'Kira Sözleşmesi'), ('PROTOKOL', 'Protokol'), ('SATIS SOZLESMESI', 'Satış Sözleşmesi'), ('SENET', 'Senet')], default='DIGER', max_length=20),
            preserve_default=False,
        ),
    ]
