# Generated by Django 5.2.7 on 2025-10-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0009_musterievraki_evrak_turu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mulk',
            name='sahip',
        ),
        migrations.AddField(
            model_name='mulk',
            name='sahipleri',
            field=models.ManyToManyField(blank=True, related_name='sahip_oldugu_mulkler', to='portfoy_yonetimi.musteri', verbose_name='Mülk Sahipleri'),
        ),
    ]
