# Generated by Django 5.2.7 on 2025-10-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0010_remove_mulk_sahip_mulk_sahipleri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mulk',
            options={'verbose_name': 'Mülk', 'verbose_name_plural': 'Mülkler'},
        ),
        migrations.AlterModelOptions(
            name='mulkfotografi',
            options={'verbose_name': 'Mülk Fotoğrafı', 'verbose_name_plural': 'Mülk Fotoğrafları'},
        ),
        migrations.AlterModelOptions(
            name='musteri',
            options={'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterField(
            model_name='mulk',
            name='aciklama',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='adres',
            field=models.CharField(max_length=255, verbose_name='Adres Detayı'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='baslik',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='brut_m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brüt M²'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='durum',
            field=models.CharField(choices=[('SATILIK', 'Satılık'), ('KIRALIK', 'Kiralık'), ('DEVREN_KIRALIK', 'Devren Kiralık'), ('SATILDI', 'Satıldı'), ('KIRALANDI', 'Kiralandı'), ('PASIF', 'Pasif')], default='SATILIK', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='ilce',
            field=models.CharField(max_length=50, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='mülk_turu',
            field=models.CharField(choices=[('KONUT', 'Konut'), ('ISYERI', 'İşyeri'), ('ARSA', 'Arsa'), ('PROJE', 'Proje')], max_length=10, verbose_name='Mülk Türü'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='net_m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Net M²'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='oda_sayisi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Oda Sayısı'),
        ),
        migrations.AlterField(
            model_name='mulk',
            name='sehir',
            field=models.CharField(max_length=50, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='mulkfotografi',
            name='aciklama',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='mulkfotografi',
            name='foto',
            field=models.ImageField(upload_to='mulk_fotograflari/', verbose_name='Fotoğraf Dosyası'),
        ),
        migrations.AlterField(
            model_name='mulkfotografi',
            name='mulk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='portfoy_yonetimi.mulk', verbose_name='İlgili Mülk'),
        ),
        migrations.AlterField(
            model_name='mulkfotografi',
            name='varsayilan',
            field=models.BooleanField(default=False, verbose_name='Varsayılan Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='ad_soyad',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='eposta',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='ikametgah_adresi',
            field=models.TextField(blank=True, null=True, verbose_name='İkametgah Adresi'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='kimlik_numarasi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='musteri_turu',
            field=models.CharField(choices=[('ALICI', 'Alıcı'), ('SATICI', 'Satıcı'), ('KIRACI', 'Kiracı'), ('KIRALAYAN', 'Kiralayan'), ('YATIRIMCI', 'Yatırımcı')], default='ALICI', max_length=10, verbose_name='Müşteri Türü'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='telefon',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='musterievraki',
            name='aciklama',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='musterievraki',
            name='evrak_turu',
            field=models.CharField(choices=[('KIRA_SOZLESMESI', 'Kira Sözleşmesi'), ('PROTOKOL', 'Protokol'), ('SATIS_SOZLESMESI', 'Satış Sözleşmesi'), ('SENET', 'Senet')], max_length=20, verbose_name='Evrak Türü'),
        ),
        migrations.AlterField(
            model_name='musterievraki',
            name='muhatap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilgili_oldugu_evraklar', to='portfoy_yonetimi.musteri', verbose_name='Muhatap (İlgili Kişi)'),
        ),
        migrations.AlterField(
            model_name='musterievraki',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evraklar', to='portfoy_yonetimi.musteri', verbose_name='Müşteri (Evrak Sahibi)'),
        ),
        migrations.AlterField(
            model_name='musterievraki',
            name='yuklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi'),
        ),
    ]
