# Generated by Django 5.2.7 on 2025-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0011_alter_mulk_options_alter_mulkfotografi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulk',
            name='kiralik_referans_kod',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Kiralık Referans Kodu (9 Haneli)'),
        ),
    ]
