# Generated by Django 5.2.7 on 2025-10-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0012_mulk_kiralik_referans_kod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mulk',
            name='kiralik_referans_kod',
        ),
    ]
