# Generated by Django 5.2.7 on 2025-10-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0013_remove_mulk_kiralik_referans_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon'),
        ),
    ]
