# Generated by Django 5.2.7 on 2025-10-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0013_remove_mulk_kiralik_referans_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulk',
            name='konut_tipi',
            field=models.CharField(choices=[('DAİRE', 'Daire'), ('DUBLEKS', 'Dublex'), ('VILLA', 'Villa'), ('MUSTAKİL', 'Mustakil')], default='DAIRE', max_length=10, verbose_name='Konut Tipi'),
            preserve_default=False,
        ),
    ]
