# Generated by Django 5.2.7 on 2025-10-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0014_mulk_konut_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulk',
            name='isyeri_tipi',
            field=models.CharField(choices=[('OFİS', 'Ofis'), ('DÜKKAN', 'Dükkan'), ('DEPO', 'Depo'), ('FABRİKA', 'Fabrika')], default='DUKKAN', max_length=10, verbose_name='İsyeri Tipi'),
            preserve_default=False,
        ),
    ]
