# Generated by Django 5.2.7 on 2025-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_yonetimi', '0014_alter_musteri_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulk',
            name='esya_durumu',
            field=models.CharField(choices=[('ESYALI', 'Eşyalı'), ('ESYASIZ', 'Eşyasız')], default='ESYASIZ', max_length=10, verbose_name='Eşya Durumu'),
        ),
    ]
